version: '3.9'

services:
  db:
    image: postgres:13.3

    container_name: pg

    ports:
      - 4000:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pi30141

    volumes:
      - baghchal-db:/var/lib/postgresql/data
  
  cache:

    image: redis

    container_name: cache

    ports:
      - 6379:6379

  
volumes:
  baghchal-db:

